// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Andrii Shylenko and kernelCAD contributors
import { describe, it, expect } from 'vitest';
import { parseGcodeHeader } from '../../../../../src/kernel/export/gcode/gcodeHeaderParser';

const FIXTURE = `
; HEADER_BLOCK_START
; generated by OrcaSlicer 2.4.2 on 2026-09-14 at 10:03:13
; total layer number: 100
; filament_density: 1.24
; max_z_height: 20.00
; filament: 1
; HEADER_BLOCK_END
G28 ; home
G1 X0 Y0 Z0.2
; total filament used [g] = 3.86
; total layers count = 100
; estimated printing time (normal mode) = 19m 33s
; estimated first layer printing time (normal mode) = 2s
; filament used [mm] = 1295.40
; filament used [cm3] = 3.12
; filament used [g] = 3.86
`;

describe('parseGcodeHeader', () => {
  it('parses estimated print time from "Xh Ym Zs" style durations', () => {
    const stats = parseGcodeHeader(FIXTURE);
    expect(stats.estimatedPrintTimeSeconds).toBe(19 * 60 + 33);
  });

  it('parses filament mass, length, layer count, and max Z', () => {
    const stats = parseGcodeHeader(FIXTURE);
    expect(stats.filamentUsedGrams).toBe(3.86);
    expect(stats.filamentUsedMeters).toBeCloseTo(1.2954, 4);
    expect(stats.layerCount).toBe(100);
    expect(stats.maxZMm).toBe(20);
  });

  it('parses an hours+minutes+seconds duration', () => {
    const stats = parseGcodeHeader('; estimated printing time (normal mode) = 1h 2m 3s\n');
    expect(stats.estimatedPrintTimeSeconds).toBe(3600 + 120 + 3);
  });

  it('returns an empty object for gcode with no recognizable header', () => {
    const stats = parseGcodeHeader('G28\nG1 X0 Y0\n');
    expect(stats).toEqual({});
  });
});
