// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Andrii Shylenko and kernelCAD contributors
// src/agent/vision/router.ts
//
// Auto-routing for the `trace_from_image` tool. Inspects the image's corner
// pixels (cheap; no opencv dependency) and the requested feature kinds, then
// picks one of `'opencv' | 'vision-llm' | 'hybrid'`.
//
// Heuristic (spec §3):
// - Uniform background AND silhouette/curve-only → `'opencv'` (free, deterministic).
// - Uniform background AND any point/bbox feature → `'hybrid'` (opencv for the
//   silhouette, LLM for the named labels).
// - Non-uniform background → `'vision-llm'` (opencv would fail on clutter).
//
// `UNIFORM_BG_THRESHOLD` was chosen empirically: PNG fixtures generated by the
// product-photo workflow corner-stddev under ~2; cluttered photos sample well
// over 20. 8 leaves comfortable headroom on both sides while still being
// uncalibrated enough to not over-fit.

import { cornerColorStdDev } from '../../lib/imageSimilarity/score';
import type { TraceBackend, TraceFeatureRequest } from './types';

/** Corner-color stddev under this value counts as a uniform background. */
export const UNIFORM_BG_THRESHOLD = 8;

/**
 * Decide which backend should handle a `trace_from_image` request.
 *
 * Pure function modulo the corner-color sample (which decodes a tiny corner of
 * the image via sharp).
 */
export async function decideBackend(
  imageBytes: Buffer,
  features: TraceFeatureRequest[],
): Promise<Exclude<TraceBackend, 'auto'>> {
  const stddev = await cornerColorStdDev(imageBytes);
  const uniformBg = stddev < UNIFORM_BG_THRESHOLD;

  const hasNamedPointOrBbox = features.some(
    (f) => f.kind === 'point' || f.kind === 'bbox',
  );

  if (!uniformBg) return 'vision-llm';
  if (hasNamedPointOrBbox) return 'hybrid';
  return 'opencv';
}
