#!/usr/bin/env node
// Generates the landing page's pricing <section> from the single source of
// truth (src/funnel/lib/pricingTiers.ts) and injects it into site/index.html
// between the <!-- PRICING:BEGIN --> / <!-- PRICING:END --> markers.
//
// This is what keeps the marketing landing and the in-app pricing page
// (src/studio/routes/pricing.tsx, which renders the SAME module) from ever
// drifting. To change prices or features, edit pricingTiers.ts — never hand-edit
// the generated block in index.html.

import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { CONTACT_HREF, PRICING_COPY, TIERS, type Tier } from '../../src/funnel/lib/pricingTiers';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const INDEX_HTML = path.resolve(__dirname, '../index.html');

/** Where the landing's paid CTAs deep-link — straight into app checkout. */
const APP_BASE = 'https://app.kernelcad.com';

const BEGIN = '<!-- PRICING:BEGIN (generated by site/scripts/build-pricing.ts — edit src/funnel/lib/pricingTiers.ts, not this block) -->';
const END = '<!-- PRICING:END -->';

function esc(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

function renderCard(t: Tier): string {
  const featured = t.popular === true;
  const per = t.contact ? 'let&rsquo;s talk' : '/ month';
  const yearly = t.yearly ? `or ${esc(t.yearly)}/yr &mdash; 2 months free` : '&nbsp;';
  const ctaClass = featured ? 'btn-primary' : 'btn-secondary';
  const cta = t.contact
    ? `<a class="btn ${ctaClass} price-cta" href="${CONTACT_HREF}">Contact sales</a>`
    : `<a class="btn ${ctaClass} price-cta" href="${APP_BASE}/pricing?buy=${t.tier}">Get ${esc(t.name)}</a>`;

  const items: string[] = [];
  if (t.inherits) items.push(`<li>Everything in ${esc(t.inherits)}</li>`);
  for (const f of t.features) items.push(`<li>${esc(f.text)}</li>`);

  return [
    `        <article class="price-card${featured ? ' price-card--featured' : ''}">`,
    featured ? '          <span class="price-badge">Most popular</span>' : null,
    `          <h3 class="price-name">${esc(t.name)}</h3>`,
    `          <p class="price-amount"><span class="price-num">${esc(t.monthly)}</span><span class="price-per">${per}</span></p>`,
    `          <p class="price-yearly">${yearly}</p>`,
    `          <p class="price-blurb">${esc(t.blurb)}</p>`,
    `          ${cta}`,
    '          <ul class="price-features">',
    ...items.map((li) => `            ${li}`),
    '          </ul>',
    '        </article>',
  ]
    .filter((line): line is string => line !== null)
    .join('\n');
}

export function renderPricingSection(): string {
  return [
    '    <section class="pricing" id="pricing" aria-label="Pricing">',
    '      <div class="pricing-head">',
    `        <span class="section-kicker">${esc(PRICING_COPY.kicker)}</span>`,
    `        <h2 class="pricing-headline">${esc(PRICING_COPY.headline)}</h2>`,
    `        <p class="pricing-sub">${esc(PRICING_COPY.sub)}</p>`,
    '      </div>',
    '      <div class="pricing-grid">',
    TIERS.map(renderCard).join('\n'),
    '      </div>',
    '    </section>',
  ].join('\n');
}

/** Replace the marked pricing block in `html` with the freshly rendered one. */
export function injectPricing(html: string): string {
  const beginIdx = html.indexOf(BEGIN);
  const endIdx = html.indexOf(END);
  if (beginIdx === -1 || endIdx === -1 || endIdx < beginIdx) {
    throw new Error(
      `Missing or malformed PRICING markers. Expected:\n  ${BEGIN}\n  ...\n  ${END}`,
    );
  }
  const before = html.slice(0, beginIdx + BEGIN.length);
  const after = html.slice(endIdx);
  return `${before}\n${renderPricingSection()}\n    ${after}`;
}

export const INDEX_HTML_PATH = INDEX_HTML;

function main(): void {
  const html = readFileSync(INDEX_HTML, 'utf8');
  const next = injectPricing(html);
  if (next !== html) {
    writeFileSync(INDEX_HTML, next);
    console.log('build-pricing: regenerated landing pricing section from pricingTiers.ts');
  } else {
    console.log('build-pricing: landing pricing section already up to date');
  }
}

// Run only when invoked directly, not when imported by the sync-guard test.
if (import.meta.url === `file://${process.argv[1]}`) {
  main();
}
