#!/usr/bin/env node
// Regenerates the landing page's pricing block in site/index.html between the
// <!-- PRICING:BEGIN --> / <!-- PRICING:END --> markers.
//
// The block is the SAME React component the in-app /pricing route renders
// (src/funnel/components/PricingSection.tsx), server-rendered here to static
// HTML as a no-JS fallback. The shipped bundle /pricing-island.js then hydrates
// it so the Monthly/Yearly toggle is live and the paid CTAs deep-link straight
// into app checkout with the selected billing period. One component, both
// surfaces — no hand-rolled second implementation to drift.
//
// To change prices/features/copy, edit src/funnel/lib/pricingTiers.ts, then run
// `npm run site:build-pricing` (rebuilds this block) and, for the interactive
// bundle, `npm run site:build-island`. `npm run site:build` does both.

import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createElement } from 'react';
import { renderToString } from 'react-dom/server';
import { PricingSection } from '../../src/funnel/components/PricingSection';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const INDEX_HTML = path.resolve(__dirname, '../index.html');

const BEGIN = '<!-- PRICING:BEGIN (generated by site/scripts/build-pricing.ts — edit src/funnel/lib/pricingTiers.ts, not this block) -->';
const END = '<!-- PRICING:END -->';

const noop = () => {};

/**
 * Server-render PricingSection to static HTML. The interactive handlers are
 * no-ops here — they exist only so the client bundle (pricing-island.tsx) can
 * hydrate this exact markup and wire the toggle + checkout deep-links.
 */
export function renderPricingSection(): string {
  const ssr = renderToString(createElement(PricingSection, { onSelect: noop, onFree: noop }));
  return [
    '    <section class="pricing" id="pricing" aria-label="Pricing">',
    // Tailwind utilities for the island (theme + utilities, no preflight so the
    // landing's own base styles survive).
    '      <link rel="stylesheet" href="/pricing-island.css" />',
    // Dark band so the app-themed dark cards read as an intentional section on
    // the light marketing page.
    `      <div id="pricing-root" class="mx-auto max-w-6xl rounded-3xl bg-[#0b0b0d] px-6 py-16 text-white">${ssr}</div>`,
    // Hydrates #pricing-root into the live PricingSection component.
    '      <script type="module" src="/pricing-island.js"></script>',
    '    </section>',
  ].join('\n');
}

/** Replace the marked pricing block in `html` with the freshly rendered one. */
export function injectPricing(html: string): string {
  const beginIdx = html.indexOf(BEGIN);
  const endIdx = html.indexOf(END);
  if (beginIdx === -1 || endIdx === -1 || endIdx < beginIdx) {
    throw new Error(
      `Missing or malformed PRICING markers. Expected:\n  ${BEGIN}\n  ...\n  ${END}`,
    );
  }
  const before = html.slice(0, beginIdx + BEGIN.length);
  const after = html.slice(endIdx);
  return `${before}\n${renderPricingSection()}\n    ${after}`;
}

export const INDEX_HTML_PATH = INDEX_HTML;

function main(): void {
  const html = readFileSync(INDEX_HTML, 'utf8');
  const next = injectPricing(html);
  if (next !== html) {
    writeFileSync(INDEX_HTML, next);
    console.log('build-pricing: regenerated landing pricing section from PricingSection.tsx');
  } else {
    console.log('build-pricing: landing pricing section already up to date');
  }
}

// Run only when invoked directly, not when imported by the sync-guard test.
if (import.meta.url === `file://${process.argv[1]}`) {
  main();
}
