// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Andrii Shylenko and kernelCAD contributors
//
// The gate on prebaked geometry.
//
// A prebaked model is a copy of an example's output, and the dangerous failure is not a
// crash — it is a page that renders a model built from source the reader is no
// longer looking at. Nothing about that looks wrong. So this file does two
// things: it proves `staleModels` actually detects the drift (with fixtures, so
// the assertions run everywhere), and it checks the real manifest whenever one
// is on disk.

import { describe, it, expect } from 'vitest';
import { existsSync, readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { buildDocsPages } from '../../src/docs/liveDocs';
import {
  DOCS_MODEL_DIR,
  DOCS_MODEL_EXT,
  DOCS_MODEL_MANIFEST,
  hashExampleCode,
  staleModels,
  type DocsModel,
  type DocsModelManifest,
} from './docsModels';

const SITE = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const pages = buildDocsPages();
const withExamples = pages.filter((p) => p.example !== null);

/** A manifest that is correct for the current examples. */
function freshManifest(): DocsModelManifest {
  return {
    models: withExamples.map((page): DocsModel => ({
      slug: page.slug,
      url: `/${DOCS_MODEL_DIR}/${page.slug}${DOCS_MODEL_EXT}`,
      codeHash: hashExampleCode(page.example!.code),
      bytes: 2048,
      bounds: { min: [0, 0, 0], max: [1, 1, 1] },
      appearances: [{}],
    })),
  };
}

describe('prebaked model staleness gate', () => {
  it('there is more than one example, so the checks below are not vacuous', () => {
    expect(withExamples.length).toBeGreaterThan(5);
  });

  it('accepts a manifest built from the current examples', () => {
    expect(staleModels(pages, freshManifest())).toEqual([]);
  });

  it('rejects a model built from different source', () => {
    // The whole reason this file exists: an example edited after its model was
    // baked. The bytes are fine, the page renders, the picture is a lie.
    const manifest = freshManifest();
    const drifted = {
      models: manifest.models.map((m, i) =>
        i === 0 ? { ...m, codeHash: hashExampleCode('const x = box(1, 1, 1);') } : m,
      ),
    };
    const failures = staleModels(pages, drifted);
    expect(failures).toHaveLength(1);
    expect(failures[0]).toContain(withExamples[0].slug);
    expect(failures[0]).toContain('different source');
  });

  it('rejects a missing model', () => {
    const manifest = freshManifest();
    const failures = staleModels(pages, { models: manifest.models.slice(1) });
    expect(failures).toEqual([`${withExamples[0].slug}: no prebaked model`]);
  });

  it('rejects an empty model', () => {
    const manifest = freshManifest();
    const failures = staleModels(pages, {
      models: manifest.models.map((m, i) => (i === 0 ? { ...m, bytes: 0 } : m)),
    });
    expect(failures).toEqual([`${withExamples[0].slug}: model is empty`]);
  });

  it('rejects no manifest at all', () => {
    expect(staleModels(pages, null)).toHaveLength(1);
  });

  it('every example page gets a model, so no page can silently ship without one', () => {
    // `staleModels` only inspects pages that HAVE an example. If that filter
    // ever inverted, every check above would pass on an empty manifest.
    expect(staleModels(pages, { models: [] })).toHaveLength(withExamples.length);
  });
});

describe('the prebaked models on disk', () => {
  const manifestPath = path.join(SITE, DOCS_MODEL_DIR, DOCS_MODEL_MANIFEST);

  // site/docs/ is a build artifact, regenerated by `npm run site:build-docs`
  // and never committed, so on a clean checkout there is nothing to check —
  // build-docs.ts is what enforces this at build time. When a build HAS run,
  // a manifest left stale by an example edit is caught here too.
  it.runIf(existsSync(manifestPath))('match the current examples', () => {
    const manifest = JSON.parse(readFileSync(manifestPath, 'utf8')) as DocsModelManifest;
    expect(staleModels(pages, manifest)).toEqual([]);
    for (const model of manifest.models) {
      const file = path.join(SITE, DOCS_MODEL_DIR, `${model.slug}${DOCS_MODEL_EXT}`);
      expect(existsSync(file), `${model.slug}${DOCS_MODEL_EXT} is in the manifest but not on disk`).toBe(true);
    }
  });
});
