// NURBS Slice B Task 10: variableSweep end-to-end integration tests.
//
// These cover the engine→lowerer round-trip when a `variableSweep` is built
// from a `nurbsCurve` (virtual `curve3d` record) spine. Before the gap fix,
// the recompute engine raised `recompute.input.missing` because the spine
// upstream record has `metadata.virtual === true` and produces no
// `ShapeBackend`. The fix lets the engine pass virtual upstream refs
// through and lets the variableSweep lowerer arm materialise the spine
// edge on-demand from `inputs.records`.

import { describe, it, expect, beforeAll } from 'vitest';
import { buildModel } from '../../src/modeling/buildModel';
import { initOcct } from '../../src/kernel/backends/occt/occtBackend';
import { CaptureSession } from '../../src/modeling/capture/captureSession';
import { createApi } from '../../src/modeling/api';
import { createOcctLowerer } from '../../src/modeling/backends/occt/occtLowerer';
import { RecomputeEngine } from '../../src/modeling/compute/recomputeEngine';
import type { FeatureRecord } from '../../src/shared/intent/featureRecord';
import type { ShapeBackend } from '../../src/kernel/backends/backend';

describe('variableSweep end-to-end (engine + lowerer)', () => {
  beforeAll(async () => {
    await initOcct();
  });

  it('lowers a tapered sweep with a NURBS curve spine + square profiles', async () => {
    // 30mm Z-axis spine — 4 collinear control points (degree-3 NURBS,
    // clamped-uniform knots auto-generated by the curve3d capture).
    const model = await buildModel({
      fileName: 'variableSweep-nurbs-spine.kcad.ts',
      code: `
        const spine = nurbsCurve([
          [0, 0, 0],
          [0, 0, 10],
          [0, 0, 20],
          [0, 0, 30],
        ], { degree: 3 });
        const profileA = path()
          .moveTo(-1, -1)
          .lineTo(1, -1)
          .lineTo(1, 1)
          .lineTo(-1, 1)
          .close();
        const profileB = path()
          .moveTo(-0.5, -0.5)
          .lineTo(0.5, -0.5)
          .lineTo(0.5, 0.5)
          .lineTo(-0.5, 0.5)
          .close();
        return variableSweep(spine, [
          { t: 0, profile: profileA },
          { t: 1, profile: profileB },
        ]);
      `,
    });

    const errs = model.diagnostics.filter((d) => d.severity === 'error');
    expect(errs).toEqual([]);
    expect(model.tailShape).toBeDefined();

    const shape = model.tailShape!;
    const v = shape.volume();
    expect(Number.isFinite(v)).toBe(true);
    expect(v).toBeGreaterThan(0);
    // Loose bounds: full upper (2x2 prism over 30mm = 120) and lower
    // (1x1 prism over 30mm = 30) are envelopes for any sane blend; the
    // taper from 2x2 to 1x1 means the actual volume sits between.
    expect(v).toBeLessThan(120);
    expect(v).toBeGreaterThan(30);

    const bbox = shape.boundingBox();
    expect(bbox.min[2]).toBeGreaterThan(-1);
    expect(bbox.max[2]).toBeLessThan(31);
    const zSpan = bbox.max[2] - bbox.min[2];
    expect(zSpan).toBeGreaterThan(28);
    expect(zSpan).toBeLessThan(31);

    // Health for the spine (virtual) and the sweep record (real BREP).
    const spineRec = model.records.find((r) => r.kind === 'curve3d');
    const sweepRec = model.records.find((r) => r.kind === 'variableSweep');
    expect(spineRec).toBeDefined();
    expect(sweepRec).toBeDefined();
    expect(model.health.get(spineRec!.id)).toBe('healthy');
    expect(model.health.get(sweepRec!.id)).toBe('healthy');
  });

  it('lowers a tapered sweep with a Sketch spine (triangle path, first edge is the rail)', async () => {
    // The capture API only emits closed sketches (`.close()` is mandatory).
    // The dispatch arm picks the lifted outer wire's first edge as the
    // spine — for a triangle (A → B → C → A), the first edge is A→B and
    // serves as a straight rail. We use a right triangle with the spine
    // leg along the X axis (0,0) → (50,0); the other two legs return to
    // origin through (50,1) so the wire is a valid closed loop.
    const model = await buildModel({
      fileName: 'variableSweep-sketch-spine.kcad.ts',
      code: `
        const spine = path()
          .moveTo(0, 0)
          .lineTo(50, 0)
          .lineTo(50, 1)
          .close();
        const profileA = path()
          .moveTo(-1, -1)
          .lineTo(1, -1)
          .lineTo(1, 1)
          .lineTo(-1, 1)
          .close();
        const profileB = path()
          .moveTo(-1, -1)
          .lineTo(1, -1)
          .lineTo(1, 1)
          .lineTo(-1, 1)
          .close();
        return variableSweep(spine, [
          { t: 0, profile: profileA },
          { t: 1, profile: profileB },
        ]);
      `,
    });

    const errs = model.diagnostics.filter((d) => d.severity === 'error');
    expect(errs).toEqual([]);
    expect(model.tailShape).toBeDefined();
    const shape = model.tailShape!;
    expect(shape.volume()).toBeGreaterThan(0);
  });

  it('emits a sharp spine diagnostic when the spine ref points at a non-curve, non-sketch feature', async () => {
    // Wire a box as the spine. The capture-time API rejects only on type
    // checks, but `addVariableSweep` accepts any FeatureId. At lower time
    // the spine resolution falls through: no curve3d on-demand path, no
    // sketch lift — must surface the structured spine diagnostic.
    await initOcct();
    const session = new CaptureSession();
    const kcad = createApi({ session });
    const wrongSpine = kcad.box(1, 1, 30);
    const profileA = kcad
      .path()
      .moveTo(-1, -1)
      .lineTo(1, -1)
      .lineTo(1, 1)
      .lineTo(-1, 1)
      .close();
    const profileB = kcad
      .path()
      .moveTo(-1, -1)
      .lineTo(1, -1)
      .lineTo(1, 1)
      .lineTo(-1, 1)
      .close();
    session.addVariableSweep({
      spineId: wrongSpine.id,
      sections: [
        { t: 0, profileId: profileA.id },
        { t: 1, profileId: profileB.id },
      ],
    });

    const engine = new RecomputeEngine(createOcctLowerer(session));
    const records: readonly FeatureRecord[] = session.getRecords();
    const result = await engine.run(records, { paramTable: session.paramTable });

    const sweepRec = records.find((r) => r.kind === 'variableSweep')!;
    expect(result.health.get(sweepRec.id)).toBe('error');
    const sweepErrs = result.diagnostics.filter(
      (d) => d.featureId === sweepRec.id && d.severity === 'error',
    );
    expect(sweepErrs.length).toBeGreaterThan(0);
    const msg = sweepErrs.map((d) => d.message).join('\n');
    // Must mention the spine resolution failure — the diagnostic is the
    // signal the agent needs to fix its model.
    expect(msg).toMatch(/spine/i);

    // No silent shape — sweep must NOT have produced output.
    const sweepShape: ShapeBackend | undefined = result.shapes.get(sweepRec.id);
    expect(sweepShape).toBeUndefined();
  });
});
