// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Andrii Shylenko and kernelCAD contributors
// scripts/lib/distPostinstallScript.ts
//
// Authors scripts/postinstall.mjs INSIDE the dist repo. The script
// PRINTS the local-MCP setup snippet for whichever agent the user
// is on; it does NOT execute npm install, and it does NOT modify
// any agent config file. The only side effect is stdout.

export function authorPostinstall({ version }: { version: string }): string {
  const minor = /^(\d+)\.(\d+)/.exec(version)?.[0] ?? '0.11';
  return `#!/usr/bin/env node
// scripts/postinstall.mjs (generated by the kernelCAD dist-skills generator)
//
// Prints setup instructions for the local kernelcad MCP. Never runs
// npm install on your behalf. Never edits any agent config file. The
// ONLY side effect is text on stdout.

const detectAgents = () => {
  const env = process.env;
  const agents = [];
  if (env.CLAUDE_CODE || env.CLAUDECODE) agents.push('claude-code');
  if (env.CURSOR_TRACE_ID || env.CURSOR) agents.push('cursor');
  if (env.CODEX || env.OPENAI_CODEX) agents.push('codex');
  if (env.COPILOT || env.GH_COPILOT) agents.push('copilot');
  return agents.length === 0 ? ['claude-code', 'cursor', 'codex', 'copilot'] : agents;
};

const SNIPPETS = {
  'claude-code': [
    'In Claude Code, register a local stdio MCP:',
    '  claude mcp add kernelcad -- kernelcad mcp',
  ].join('\\n'),
  'cursor': [
    'In Cursor, add the kernelcad MCP entry to your MCP config:',
    '  { "mcpServers": { "kernelcad": { "command": "kernelcad", "args": ["mcp"] } } }',
  ].join('\\n'),
  'codex': [
    'In Codex, add the kernelcad MCP entry to your MCP config:',
    '  [mcp_servers.kernelcad]',
    '  command = "kernelcad"',
    '  args = ["mcp"]',
  ].join('\\n'),
  'copilot': [
    'In GitHub Copilot, add the kernelcad MCP entry to your settings:',
    '  "mcp.servers": { "kernelcad": { "command": "kernelcad", "args": ["mcp"] } }',
  ].join('\\n'),
};

console.log('');
console.log('kernelCAD skills installed.');
console.log('');
console.log('Local MCP (default): run \`kernelcad mcp\` as a stdio server.');
console.log('  If kernelcad is not on PATH, install it:');
console.log('    npm i -g kernelcad@^${minor}');
console.log('');
console.log('Register the MCP with your agent:');
for (const agent of detectAgents()) {
  console.log('');
  console.log('— ' + agent + ' —');
  console.log(SNIPPETS[agent]);
}
console.log('');
console.log('Hosted MCP (opt-in fallback): set KERNELCAD_API_KEY and point your agent at');
console.log('  https://api.kernelcad.com/mcp');
console.log('');
`;
}
