// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Andrii Shylenko and kernelCAD contributors
// src/modeling/spurGear.ts
//
// Pure involute spur-gear profile generator for `spurGear(...)`.
//
// The tooth is GENERATED, not drawn: the profile is the material a standard
// basic rack (straight flanks at the pressure angle, sharp tip at the
// dedendum) leaves behind when it rolls on the pitch circle. At every radius
// r the tooth half-angle T(r) is the smallest polar angle any point of the
// rack's flank reaches at that radius over the whole roll. That one rule
// yields, without special cases:
//   - the true involute above the base circle (the envelope of the flank),
//   - the trochoidal root fillet traced by the rack tip corner,
//   - the undercut of low tooth counts (the trochoid cuts into the involute),
//   - a flat root arc between teeth at the root circle.
// Gears generated by the same rack are conjugate, so any two gears of equal
// module and pressure angle mesh at centre distance m(z1 + z2)/2.
//
// The result is ONE closed CCW polygon — tooth 0 is centred on +X — so the
// extruded body is a single manifold solid for every tooth count.

import { invalidArgsText } from '../shared/intent/invalidArgs';

export interface SpurGearProfileOptions {
  /** Module m in mm (pitch diameter / tooth count). */
  module: number;
  /** Tooth count z. */
  teeth: number;
  /** Pressure angle in degrees. */
  pressureAngleDeg: number;
  /** Circular backlash in mm at the pitch circle when this gear meshes with a
   *  gear built with the same value. Each gear thins its tooth by half. */
  backlash: number;
}

export interface SpurGearRadii {
  pitch: number;
  base: number;
  tip: number;
  root: number;
}

/** Addendum and dedendum coefficients of the standard basic rack. */
export const SPUR_GEAR_ADDENDUM = 1;
export const SPUR_GEAR_DEDENDUM = 1.25;

export function spurGearRadii(module: number, teeth: number, pressureAngleDeg: number): SpurGearRadii {
  const pitch = (module * teeth) / 2;
  return {
    pitch,
    base: pitch * Math.cos((pressureAngleDeg * Math.PI) / 180),
    tip: pitch + SPUR_GEAR_ADDENDUM * module,
    root: pitch - SPUR_GEAR_DEDENDUM * module,
  };
}

/**
 * Tooth half-angle (radians) at radius `r`, measured from the tooth centre.
 *
 * Rack frame: the pitch line is x = rp, the rack slides along +y by s = rp·θ
 * while the gear turns by θ. The rack tooth that cuts the space on the +
 * side of tooth 0 is centred at y = s + πm/2. Its flank point at depth d
 * below the pitch line sits at (rp − d, s + πm/2 − w(d)), with half-width
 * w(d) = πm/4 + backlash/4 − d·tan α. In gear coordinates that point has
 * polar angle atan2(u, rp − d) − θ, where u is its world y.
 */
function makeHalfAngleFn(opts: SpurGearProfileOptions): (r: number) => number {
  const m = opts.module;
  const alpha = (opts.pressureAngleDeg * Math.PI) / 180;
  const tanA = Math.tan(alpha);
  const rp = (m * opts.teeth) / 2;
  const y0 = (Math.PI * m) / 2;
  const wp = (Math.PI * m) / 4 + opts.backlash / 4;
  const dMax = SPUR_GEAR_DEDENDUM * m;
  // The rack flank above the pitch line only matters up to the gear tip.
  const dMinGlobal = -SPUR_GEAR_ADDENDUM * m;

  // Polar angle of the flank point at depth d when it crosses radius r;
  // both crossings (u = ±v) are removed material, so take the smaller.
  const angleAt = (r: number, d: number): number => {
    const x = rp - d;
    const v2 = r * r - x * x;
    if (v2 < 0) return Number.POSITIVE_INFINITY;
    const v = Math.sqrt(v2);
    const w = wp - d * tanA;
    const aNeg = Math.atan2(-v, x) - (-v - y0 + w) / rp;
    const aPos = Math.atan2(v, x) - (v - y0 + w) / rp;
    return Math.min(aNeg, aPos);
  };

  return (r: number): number => {
    const dLo = Math.max(dMinGlobal, rp - r);
    const dHi = dMax;
    if (dLo > dHi) return Number.POSITIVE_INFINITY;
    // Coarse scan over the flank, then golden-section refine around the best
    // sample. The involute is an interior minimum (the flank envelope); the
    // fillet is the endpoint d = dMax (the rack tip corner).
    const N = 64;
    let bestI = 0;
    let best = Number.POSITIVE_INFINITY;
    for (let i = 0; i <= N; i += 1) {
      const a = angleAt(r, dLo + ((dHi - dLo) * i) / N);
      if (a < best) {
        best = a;
        bestI = i;
      }
    }
    let lo = dLo + ((dHi - dLo) * Math.max(0, bestI - 1)) / N;
    let hi = dLo + ((dHi - dLo) * Math.min(N, bestI + 1)) / N;
    const g = (Math.sqrt(5) - 1) / 2;
    let c = hi - g * (hi - lo);
    let e = lo + g * (hi - lo);
    let fc = angleAt(r, c);
    let fe = angleAt(r, e);
    for (let k = 0; k < 40; k += 1) {
      if (fc < fe) {
        hi = e;
        e = c;
        fe = fc;
        c = hi - g * (hi - lo);
        fc = angleAt(r, c);
      } else {
        lo = c;
        c = e;
        fc = fe;
        e = lo + g * (hi - lo);
        fe = angleAt(r, e);
      }
    }
    return Math.min(best, fc, fe, angleAt(r, dLo), angleAt(r, dHi));
  };
}

/** Radii sampled along one flank, root → tip. Dense near the root (where the
 *  fillet turns fast) and near the base circle (where the involute starts). */
function flankRadii(radii: SpurGearRadii, samples: number): number[] {
  const out: number[] = [];
  const span = radii.tip - radii.root;
  for (let i = 0; i <= samples; i += 1) {
    const t = i / samples;
    // Quadratic spacing: fine steps at the root, coarser toward the tip.
    out.push(radii.root + span * t * t * (3 - 2 * t) * 0.35 + span * t * 0.65);
  }
  if (radii.base > radii.root && radii.base < radii.tip) out.push(radii.base);
  out.sort((a, b) => a - b);
  return out.filter((r, i) => i === 0 || r - out[i - 1] > 1e-6 * span);
}

/**
 * `spurGear` / `internalSpurGear` / `planetaryToothCompatibility` re-raise
 * these as `feature.invalid-args` (see `apiShapeMethods`), so build the
 * message and hint with the shared raiser's renderer: API + argument path,
 * received value, requirement, inline example.
 */
function profileError(spec: Parameters<typeof invalidArgsText>[0]): SpurGearProfileError {
  const { message, hint } = invalidArgsText(spec);
  return new SpurGearProfileError(message, hint);
}

export class SpurGearProfileError extends Error {
  readonly hint: string;
  constructor(message: string, hint: string) {
    super(message);
    this.name = 'SpurGearProfileError';
    this.hint = hint;
  }
}

/** One segment of the gear outline, in path order. */
export type SpurGearSegment =
  | { kind: 'spline'; points: Array<[number, number]> }
  | { kind: 'arc'; to: [number, number]; mid: [number, number] };

export interface SpurGearOutline {
  start: [number, number];
  segments: SpurGearSegment[];
  radii: SpurGearRadii;
}

/** Sampled tooth half-angle along the flank, root → tip, plus the index of
 *  the first sample on the involute (the fillet/involute junction, where the
 *  outline may have a corner when the root is undercut). */
export interface SpurGearFlankSamples {
  radii: SpurGearRadii;
  rs: number[];
  ts: number[];
  involuteStart: number;
}

export function spurGearFlankSamples(
  opts: SpurGearProfileOptions,
  flankSamples = 12,
): SpurGearFlankSamples {
  const z = opts.teeth;
  const radii = spurGearRadii(opts.module, z, opts.pressureAngleDeg);
  const halfAngle = makeHalfAngleFn(opts);
  const pitchAngle = (2 * Math.PI) / z;
  const alpha = (opts.pressureAngleDeg * Math.PI) / 180;
  const inv = (a: number): number => Math.tan(a) - a;
  const tPitch = Math.PI / (2 * z) - opts.backlash / (4 * radii.pitch) + inv(alpha);
  // Analytic involute half-angle; defined from the base circle outward.
  const involuteHalf = (r: number): number => tPitch - inv(Math.acos(Math.min(1, radii.base / r)));

  const rs = flankRadii(radii, flankSamples);
  // Undercut: the rack tip's trochoid cuts the involute foot, leaving a
  // corner where the two meet. Find that radius and sample it exactly so the
  // outline keeps the corner instead of smoothing across it.
  if (radii.base > radii.root && halfAngle(radii.base) < involuteHalf(radii.base) - 1e-6) {
    let lo = radii.base;
    let hi = radii.tip;
    for (let k = 0; k < 60; k += 1) {
      const mid = (lo + hi) / 2;
      if (halfAngle(mid) < involuteHalf(mid) - 1e-9) lo = mid;
      else hi = mid;
    }
    rs.push(hi);
    rs.sort((a, b) => a - b);
  }
  const ts = rs.map((r) => halfAngle(r));

  for (let i = 0; i < rs.length; i += 1) {
    const t = ts[i];
    if (!Number.isFinite(t) || t <= 0) {
      throw profileError({
        api: 'spurGear({ teeth, pressureAngle, backlash })',
        path: 'opts.teeth + opts.pressureAngle + opts.backlash',
        gotText: `teeth ${z}, pressureAngle ${opts.pressureAngleDeg} deg, backlash ${opts.backlash} mm — the tooth flank vanishes at radius ${rs[i].toFixed(3)} mm`,
        requires:
          'a combination whose tooth survives to the root: raise teeth, raise pressureAngle, or lower backlash (backlash must stay well under the module)',
        example: 'spurGear({ module: 1, teeth: 20, faceWidth: 6, bore: 5 })',
      });
    }
    if (t >= pitchAngle / 2) {
      throw profileError({
        api: 'spurGear({ module, teeth, pressureAngle })',
        path: 'opts.module + opts.teeth + opts.pressureAngle',
        gotText: `a tooth space that closes up — neighbouring teeth touch at radius ${rs[i].toFixed(3)} mm`,
        requires:
          'a combination that leaves a tooth space: raise teeth for the same module, or lower pressureAngle',
        example: 'spurGear({ module: 1, teeth: 20, faceWidth: 6, bore: 5 })',
      });
    }
  }
  const tipHalf = ts[ts.length - 1];
  if (tipHalf * radii.tip < 0.05 * opts.module) {
    throw profileError({
      api: 'spurGear({ module, teeth, pressureAngle })',
      path: 'opts.teeth + opts.pressureAngle',
      gotText: `a pointed tooth — the tip land is ${(2 * tipHalf * radii.tip).toFixed(3)} mm, under the 0.05 × module floor of ${(0.05 * opts.module).toFixed(3)} mm`,
      requires: 'a combination with a flat tip land: raise teeth, lower pressureAngle, or lower backlash',
      unit: 'mm',
      example: 'spurGear({ module: 1, teeth: 20, faceWidth: 6, bore: 5 })',
    });
  }

  // First sample that lies on the analytic involute (1e-5 rad absorbs the
  // numeric minimisation noise at the base-circle cusp).
  let involuteStart = rs.length - 1;
  for (let i = 0; i < rs.length; i += 1) {
    if (rs[i] < radii.base) continue;
    if (Math.abs(involuteHalf(rs[i]) - ts[i]) < 1e-5) {
      involuteStart = i;
      break;
    }
  }
  return { radii, rs, ts, involuteStart };
}

/**
 * Build the closed CCW outline of an involute spur gear, tooth 0 centred on
 * +X, as path segments: per tooth a fillet spline and an involute spline on
 * each flank, a tip-land arc and a root arc. Throws `SpurGearProfileError`
 * when the parameters give a pointed or self-intersecting tooth.
 */
export function spurGearOutline(opts: SpurGearProfileOptions): SpurGearOutline {
  const z = opts.teeth;
  const { radii, rs, ts, involuteStart } = spurGearFlankSamples(opts);
  const pitchAngle = (2 * Math.PI) / z;
  const polar = (r: number, a: number): [number, number] => [r * Math.cos(a), r * Math.sin(a)];
  // Split each flank at the fillet/involute junction (a corner when the root
  // is undercut); a part with a single sample collapses into its neighbour.
  const parts: Array<[number, number]> = involuteStart > 0 && involuteStart < rs.length - 1
    ? [[0, involuteStart], [involuteStart, rs.length - 1]]
    : [[0, rs.length - 1]];

  const segments: SpurGearSegment[] = [];
  const rootHalf = ts[0];
  const tipHalf = ts[ts.length - 1];
  for (let k = 0; k < z; k += 1) {
    const c = k * pitchAngle;
    // Leading (−) flank, root → tip.
    for (const [i0, i1] of parts) {
      const points: Array<[number, number]> = [];
      for (let i = i0; i <= i1; i += 1) points.push(polar(rs[i], c - ts[i]));
      segments.push({ kind: 'spline', points });
    }
    // Tip land.
    segments.push({ kind: 'arc', mid: polar(radii.tip, c), to: polar(radii.tip, c + tipHalf) });
    // Trailing (+) flank, tip → root.
    for (const [i0, i1] of [...parts].reverse()) {
      const points: Array<[number, number]> = [];
      for (let i = i1; i >= i0; i -= 1) points.push(polar(rs[i], c + ts[i]));
      segments.push({ kind: 'spline', points });
    }
    // Root arc to the next tooth's leading flank.
    const next = c + pitchAngle - rootHalf;
    segments.push({
      kind: 'arc',
      mid: polar(radii.root, (c + rootHalf + next) / 2),
      to: polar(radii.root, next),
    });
  }
  return { start: polar(radii.root, -rootHalf), segments, radii };
}

/** Invert a point through the pitch circle: r' = 2·pitch − r (same polar angle).
 *  Maps an external spur outline onto the internal-tooth bore cutter. */
export function invertAroundPitch(
  point: readonly [number, number],
  pitch: number,
): [number, number] {
  const r = Math.hypot(point[0], point[1]);
  if (r < 1e-12) return [0, 0];
  const scale = (2 * pitch - r) / r;
  return [point[0] * scale, point[1] * scale];
}

/**
 * Mirror an external spur outline around its pitch circle to get the bore
 * cutter for an internal / ring gear. Tip ↔ root swap radially; winding is
 * preserved in sample order (gallery / OCCT path builders tolerate it when
 * the path is closed before extrude).
 */
export function internalSpurGearBoreOutline(opts: SpurGearProfileOptions): SpurGearOutline {
  const external = spurGearOutline(opts);
  const pitch = external.radii.pitch;
  const invertSeg = (seg: SpurGearSegment): SpurGearSegment => {
    if (seg.kind === 'spline') {
      return { kind: 'spline', points: seg.points.map((p) => invertAroundPitch(p, pitch)) };
    }
    return {
      kind: 'arc',
      mid: invertAroundPitch(seg.mid, pitch),
      to: invertAroundPitch(seg.to, pitch),
    };
  };
  return {
    start: invertAroundPitch(external.start, pitch),
    segments: external.segments.map(invertSeg),
    radii: {
      pitch,
      // After inversion tip is inward, root is the deepest bore radius.
      tip: 2 * pitch - external.radii.tip,
      root: 2 * pitch - external.radii.root,
      base: 2 * pitch - external.radii.base,
    },
  };
}

export interface PlanetaryToothCompatibility {
  readonly sunTeeth: number;
  readonly planetTeeth: number;
  readonly ringTeeth: number;
}

/**
 * Standard coaxial planetary pitch constraint: Zring = Zsun + 2·Zplanet.
 * Same module and pressure angle are assumed for all three members.
 */
export function assertPlanetaryToothCompatibility(opts: PlanetaryToothCompatibility): void {
  const { sunTeeth, planetTeeth, ringTeeth } = opts;
  for (const [label, value] of [
    ['sunTeeth', sunTeeth],
    ['planetTeeth', planetTeeth],
    ['ringTeeth', ringTeeth],
  ] as const) {
    if (typeof value !== 'number' || !Number.isInteger(value) || value < 6) {
      throw profileError({
        api: `planetaryToothCompatibility({ ${label} })`,
        path: `opts.${label}`,
        got: value,
        showType: typeof value !== 'number',
        requires: 'a whole tooth count ≥ 6',
        unit: 'count',
        example: 'planetaryToothCompatibility({ sunTeeth: 18, planetTeeth: 18, ringTeeth: 54 })',
      });
    }
  }
  const expected = sunTeeth + 2 * planetTeeth;
  if (ringTeeth !== expected) {
    throw profileError({
      api: 'planetaryToothCompatibility({ ringTeeth })',
      path: 'opts.ringTeeth',
      got: ringTeeth,
      requires:
        `ringTeeth = sunTeeth + 2 × planetTeeth — sunTeeth is ${sunTeeth} and planetTeeth is ${planetTeeth}, so ringTeeth must be ${expected}; only then do the pitch circles meet (planet centre distance m(Zsun+Zplanet)/2, ring pitch radius m·Zring/2)`,
      unit: 'count',
      example: `planetaryToothCompatibility({ sunTeeth: ${sunTeeth}, planetTeeth: ${planetTeeth}, ringTeeth: ${expected} })`,
    });
  }
}
