// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Andrii Shylenko and kernelCAD contributors
import { describe, it, expect } from 'vitest';
import {
  attributionGenerator,
  attributionUrl,
  KERNELCAD_APP_URL,
  KERNELCAD_HOMEPAGE,
  xmlAttributionComment,
} from './attribution';

describe('attribution', () => {
  it('names kernelCAD, its version and homepage', () => {
    expect(attributionGenerator('1.2.3')).toBe('kernelCAD 1.2.3 (https://kernelcad.com)');
    expect(KERNELCAD_HOMEPAGE).toBe('https://kernelcad.com');
    expect(KERNELCAD_APP_URL).toBe('https://app.kernelcad.com');
  });

  it('tags our own links with the surface', () => {
    expect(attributionUrl('embed')).toBe('https://kernelcad.com/?ref=embed&utm_source=kernelcad&utm_medium=embed');
    expect(attributionUrl('share', `${KERNELCAD_APP_URL}/pricing?x=1`))
      .toBe('https://app.kernelcad.com/pricing?x=1&ref=share&utm_source=kernelcad&utm_medium=share');
  });

  it('is idempotent', () => {
    const once = attributionUrl('embed');
    expect(attributionUrl('embed', once)).toBe(once);
  });

  it('builds a valid XML comment', () => {
    expect(xmlAttributionComment('1.0.0')).toBe('<!-- Generated by kernelCAD 1.0.0 (https://kernelcad.com) -->');
    const inner = xmlAttributionComment('a--b').slice('<!--'.length, -'-->'.length);
    expect(inner).not.toContain('--');
  });
});
