// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Andrii Shylenko and kernelCAD contributors
// src/agent/mcp/tools/diffGeometryRender.ts
//
// Optional PNG overlay for `diff_geometry` — added material green, removed
// material red — for the human at the END of the loop. The agent's own
// evidence is the numeric table; this is the picture it hands a reviewer.
//
// It does NOT contain a renderer. The delta solids (B−A and A−B, already
// computed as OCCT shapes) are written as watertight STL sidecars, a tiny
// generated `.kcad.ts` re-imports them with `lib.fromSTL` and tags each with
// a `.finish()` colour, and that script goes through `render_preview`
// unchanged — the same headless pipeline `kernelcad render` uses.
//
// Fails OPEN, never silently: if the render pipeline is unavailable (no
// prebuilt headless player and no dev server), the overlay reports ok:false
// with the pipeline's own message and the numeric diff is still returned.

import { mkdir, mkdtemp, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import type { OcctBackend } from '../../../kernel/backends/occt/occtBackend';
import type { CompilerDiagnostic } from '../../../shared/diagnostics/diagnostic';
import { renderPreviewTool } from './renderPreview';

/** Green for material that APPEARED in the revision. */
const ADDED_COLOR = '#2ecc71';
/** Red for material that VANISHED from the baseline. */
const REMOVED_COLOR = '#e74c3c';

export interface DiffOverlayRender {
  ok: boolean;
  /** Absolute PNG paths on the MCP server's filesystem (on success). */
  images?: string[];
  /** Directory holding the overlay script, its STL inputs, and the PNGs. */
  out_dir?: string;
  /** The generated overlay script — readable, re-runnable, not a black box. */
  script_path?: string;
  /** Solids that went into the overlay. */
  addedBodies?: string[];
  removedBodies?: string[];
  error?: string;
}

export interface OverlayPair {
  base: { name: string; shape: OcctBackend };
  revised: { name: string; shape: OcctBackend };
}

function slug(name: string): string {
  return name.replace(/[^A-Za-z0-9_-]+/g, '_').replace(/^_+|_+$/g, '') || 'body';
}

/** Clone-both-operands boolean, matching the diff's own convention. Returns
 *  undefined when the result is empty or the boolean refused. */
function deltaSolid(a: OcctBackend, b: OcctBackend): OcctBackend | undefined {
  try {
    const out = a.clone().subtract(b.clone());
    return out.isEmpty() ? undefined : out;
  } catch {
    return undefined;
  }
}

export async function renderDiffOverlay(
  pairs: readonly OverlayPair[],
  outDir?: string,
): Promise<{ render: DiffOverlayRender; diagnostics: CompilerDiagnostic[] }> {
  const diagnostics: CompilerDiagnostic[] = [];
  const dir = outDir !== undefined
    ? resolve(outDir)
    : await mkdtemp(join(tmpdir(), 'kernelcad-diff-overlay-'));
  await mkdir(dir, { recursive: true });

  const imports: string[] = [];
  const terms: string[] = [];
  const addedBodies: string[] = [];
  const removedBodies: string[] = [];

  for (const pair of pairs) {
    const id = slug(pair.base.name);
    const added = deltaSolid(pair.revised.shape, pair.base.shape);
    const removed = deltaSolid(pair.base.shape, pair.revised.shape);

    if (added !== undefined) {
      const file = `added-${id}.stl`;
      await writeFile(join(dir, file), Buffer.from(await added.exportSTLAsync()));
      const binding = `added_${id}`;
      imports.push(`const ${binding} = await lib.fromSTL('./${file}');`);
      terms.push(`${binding}.finish('paint-matte', { color: '${ADDED_COLOR}' })`);
      addedBodies.push(pair.base.name);
    }
    if (removed !== undefined) {
      const file = `removed-${id}.stl`;
      await writeFile(join(dir, file), Buffer.from(await removed.exportSTLAsync()));
      const binding = `removed_${id}`;
      imports.push(`const ${binding} = await lib.fromSTL('./${file}');`);
      terms.push(`${binding}.finish('paint-matte', { color: '${REMOVED_COLOR}' })`);
      removedBodies.push(pair.base.name);
    }
  }

  if (terms.length === 0) {
    return {
      render: {
        ok: true,
        out_dir: dir,
        images: [],
        addedBodies: [],
        removedBodies: [],
      },
      diagnostics,
    };
  }

  const script = [
    '// Generated by diff_geometry({ render: true }) — added material is green,',
    `// removed material is red. Re-runnable: kernelcad render inspect <this file> <outDir>.`,
    ...imports,
    `return ${terms.join('\n  .union(')}${')'.repeat(terms.length - 1)};`,
    '',
  ].join('\n');

  const scriptPath = join(dir, 'diff-overlay.kcad.ts');
  await writeFile(scriptPath, script, 'utf8');

  const preview = await renderPreviewTool({ file: scriptPath, out_dir: dir, views: ['iso'] });
  if (!preview.ok) {
    return {
      render: {
        ok: false,
        out_dir: dir,
        script_path: scriptPath,
        addedBodies,
        removedBodies,
        error: preview.error ?? 'render_preview did not produce an overlay image.',
      },
      diagnostics: [...diagnostics, ...(preview.diagnostics ?? [])],
    };
  }

  return {
    render: {
      ok: true,
      out_dir: dir,
      script_path: scriptPath,
      images: (preview.images ?? []).map((i) => i.path),
      addedBodies,
      removedBodies,
    },
    diagnostics,
  };
}
