// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Andrii Shylenko and kernelCAD contributors
//
// Overlay scene for render_preview({ overlay: 'zebra' | 'curvature' | 'continuity' }).
// Reuses the FEA heatmap path: band the mesh into coloured STL bodies, write a
// tiny .kcad.ts, and let the existing renderer draw it. Numbers stay on inspect;
// the PNG is for locating the problem.
import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import type { Face } from 'replicad';
import { binaryStl } from '../../../kernel/fea/heatmap';
import { meshShape } from '../../../kernel/backends/occt/meshing';
import {
  continuityClassColor,
  evalSurfaceProps,
  inspectContinuity,
  inspectCurvature,
  vertexCurvatureColor,
  zebraStripe,
  type ContinuityClass,
} from '../../../kernel/backends/occt/surfaceQuality';
import { loadInspectOcctShape } from './inspectShapeLoad';
import type { Vec3 } from '../../../shared/intent/types';

export type SurfaceQualityOverlay = 'zebra' | 'curvature' | 'continuity';

export const SURFACE_QUALITY_OVERLAYS: readonly SurfaceQualityOverlay[] = ['zebra', 'curvature', 'continuity'];

type Tri = readonly [readonly number[], readonly number[], readonly number[]];

function hex(rgb: [number, number, number]): string {
  return `#${rgb.map(c => c.toString(16).padStart(2, '0')).join('')}`;
}

function triOf(verts: ArrayLike<number>, i0: number, i1: number, i2: number): Tri {
  return [
    [verts[i0 * 3], verts[i0 * 3 + 1], verts[i0 * 3 + 2]],
    [verts[i1 * 3], verts[i1 * 3 + 1], verts[i1 * 3 + 2]],
    [verts[i2 * 3], verts[i2 * 3 + 1], verts[i2 * 3 + 2]],
  ];
}

function tubeTris(a: Vec3, b: Vec3, radius: number): Tri[] {
  const dx = b[0] - a[0], dy = b[1] - a[1], dz = b[2] - a[2];
  const len = Math.hypot(dx, dy, dz);
  if (len < 1e-9) return [];
  const t: Vec3 = [dx / len, dy / len, dz / len];
  const aux: Vec3 = Math.abs(t[2]) < 0.9 ? [0, 0, 1] : [1, 0, 0];
  const n1raw: Vec3 = [
    t[1] * aux[2] - t[2] * aux[1],
    t[2] * aux[0] - t[0] * aux[2],
    t[0] * aux[1] - t[1] * aux[0],
  ];
  const n1l = Math.hypot(...n1raw) || 1;
  const n1: Vec3 = [n1raw[0] / n1l * radius, n1raw[1] / n1l * radius, n1raw[2] / n1l * radius];
  const n2raw: Vec3 = [
    t[1] * n1[2] - t[2] * n1[1],
    t[2] * n1[0] - t[0] * n1[2],
    t[0] * n1[1] - t[1] * n1[0],
  ];
  const n2l = Math.hypot(...n2raw) || 1;
  const n2: Vec3 = [n2raw[0] / n2l * radius, n2raw[1] / n2l * radius, n2raw[2] / n2l * radius];
  const a0: Vec3 = [a[0] + n1[0], a[1] + n1[1], a[2] + n1[2]];
  const a1: Vec3 = [a[0] + n2[0], a[1] + n2[1], a[2] + n2[2]];
  const a2: Vec3 = [a[0] - n1[0], a[1] - n1[1], a[2] - n1[2]];
  const a3: Vec3 = [a[0] - n2[0], a[1] - n2[1], a[2] - n2[2]];
  const b0: Vec3 = [b[0] + n1[0], b[1] + n1[1], b[2] + n1[2]];
  const b1: Vec3 = [b[0] + n2[0], b[1] + n2[1], b[2] + n2[2]];
  const b2: Vec3 = [b[0] - n1[0], b[1] - n1[1], b[2] - n1[2]];
  const b3: Vec3 = [b[0] - n2[0], b[1] - n2[1], b[2] - n2[2]];
  return [
    [a0, a1, b1], [a0, b1, b0],
    [a1, a2, b2], [a1, b2, b1],
    [a2, a3, b3], [a2, b3, b2],
    [a3, a0, b0], [a3, b0, b3],
  ];
}

async function writeOverlayScript(
  outDir: string,
  bands: Array<{ color: string; tris: Tri[]; name: string }>,
): Promise<string> {
  const imports: string[] = [];
  for (const band of bands) {
    if (band.tris.length === 0) continue;
    const stlPath = join(outDir, `${band.name}.stl`);
    await writeFile(stlPath, binaryStl(band.tris));
    imports.push(
      `arm.part('${band.name}', (await lib.fromSTL('./${band.name}.stl', { allowOpen: true })).color('${band.color}'));`,
    );
  }
  const script = [
    '// GENERATED by kernelCAD surface-quality overlay.',
    "const arm = assembly('surface-quality-overlay');",
    ...imports,
    'return arm.model();',
    '',
  ].join('\n');
  const scriptPath = join(outDir, 'overlay.kcad.ts');
  await writeFile(scriptPath, script, 'utf8');
  return scriptPath;
}

export async function buildSurfaceQualityOverlay(args: {
  file?: string;
  code?: string;
  overlay: SurfaceQualityOverlay;
  outDir: string;
}): Promise<{ ok: true; scriptPath: string } | { ok: false; error: string; errorCode?: string }> {
  const loaded = await loadInspectOcctShape({ file: args.file, code: args.code });
  if (!loaded.ok) return loaded;
  const overlayDir = join(args.outDir, 'overlay');
  await mkdir(overlayDir, { recursive: true });
  const shape = loaded.shape.getReplicadShape();
  const mesh = meshShape(shape);
  if (!mesh || mesh.faces.length === 0) {
    return { ok: false, error: 'Overlay: the shape produced no mesh faces.', errorCode: 'feature.kernel-failed' };
  }

  if (args.overlay === 'continuity') {
    const reports = inspectContinuity(loaded.shape);
    const byClass: Record<ContinuityClass, Tri[]> = { G0: [], G1: [], G2: [], broken: [] };
    let minX = Infinity, maxX = -Infinity;
    for (const f of mesh.faces) {
      for (let i = 0; i < f.vertices.length; i += 3) {
        const x = f.vertices[i];
        if (x < minX) minX = x;
        if (x > maxX) maxX = x;
      }
    }
    const radius = Math.max(0.15, (maxX - minX) * 0.008);
    const allEdges = (shape as unknown as { edges: Array<{ pointAt: (t: number) => { x: number; y: number; z: number } }> }).edges;
    for (const r of reports) {
      const edge = allEdges[r.edgeIndex];
      if (!edge) continue;
      const n = 8;
      for (let i = 0; i < n; i++) {
        const a = edge.pointAt(i / n);
        const b = edge.pointAt((i + 1) / n);
        byClass[r.class].push(...tubeTris([a.x, a.y, a.z], [b.x, b.y, b.z], radius));
      }
    }
    // Ghost body so the edges have a silhouette.
    const ghost: Tri[] = [];
    for (const face of mesh.faces) {
      for (let i = 0; i < face.indices.length; i += 3) {
        ghost.push(triOf(face.vertices, face.indices[i], face.indices[i + 1], face.indices[i + 2]));
      }
    }
    const bands = [
      { name: 'ghost', color: '#b8bcc0', tris: ghost },
      { name: 'g2', color: continuityClassColor('G2'), tris: byClass.G2 },
      { name: 'g1', color: continuityClassColor('G1'), tris: byClass.G1 },
      { name: 'g0', color: continuityClassColor('G0'), tris: byClass.G0 },
      { name: 'broken', color: continuityClassColor('broken'), tris: byClass.broken },
    ];
    const scriptPath = await writeOverlayScript(overlayDir, bands);
    return { ok: true, scriptPath };
  }

  const BANDS = 8;
  const buckets: Tri[][] = Array.from({ length: BANDS }, () => []);
  const faces = Array.from((shape as unknown as { faces: Face[] }).faces);

  if (args.overlay === 'zebra') {
    for (const face of mesh.faces) {
      for (let i = 0; i < face.indices.length; i += 3) {
        const i0 = face.indices[i], i1 = face.indices[i + 1], i2 = face.indices[i + 2];
        const n: Vec3 = [
          (face.normals[i0 * 3] + face.normals[i1 * 3] + face.normals[i2 * 3]) / 3,
          (face.normals[i0 * 3 + 1] + face.normals[i1 * 3 + 1] + face.normals[i2 * 3 + 1]) / 3,
          (face.normals[i0 * 3 + 2] + face.normals[i1 * 3 + 2] + face.normals[i2 * 3 + 2]) / 3,
        ];
        const s = (zebraStripe(n) + 1) / 2;
        const band = Math.min(BANDS - 1, Math.max(0, Math.floor(s * BANDS)));
        buckets[band].push(triOf(face.vertices, i0, i1, i2));
      }
    }
    const bands = buckets.map((tris, i) => {
      const g = Math.round((i / (BANDS - 1)) * 255);
      return { name: `zebra-${i}`, color: hex([g, g, g]), tris };
    });
    const scriptPath = await writeOverlayScript(overlayDir, bands);
    return { ok: true, scriptPath };
  }

  // curvature
  const curv = inspectCurvature(loaded.shape);
  const kByFace = new Map(curv.map(c => [c.faceIndex, c]));
  let kMin = Infinity, kMax = -Infinity;
  for (const c of curv) {
    if (c.gaussian.min < kMin) kMin = c.gaussian.min;
    if (c.gaussian.max > kMax) kMax = c.gaussian.max;
  }
  if (!Number.isFinite(kMin) || !Number.isFinite(kMax)) {
    kMin = 0;
    kMax = 0;
  }
  for (const face of mesh.faces) {
    const stats = kByFace.get(face.faceId);
    const occFace = faces[face.faceId];
    for (let i = 0; i < face.indices.length; i += 3) {
      const i0 = face.indices[i], i1 = face.indices[i + 1], i2 = face.indices[i + 2];
      let k = stats?.gaussian.mean ?? 0;
      if (occFace) {
        const cx = (face.vertices[i0 * 3] + face.vertices[i1 * 3] + face.vertices[i2 * 3]) / 3;
        const cy = (face.vertices[i0 * 3 + 1] + face.vertices[i1 * 3 + 1] + face.vertices[i2 * 3 + 1]) / 3;
        const cz = (face.vertices[i0 * 3 + 2] + face.vertices[i1 * 3 + 2] + face.vertices[i2 * 3 + 2]) / 3;
        try {
          const uv = occFace.uvCoordinates({ x: cx, y: cy, z: cz } as Parameters<Face['uvCoordinates']>[0]);
          const p = evalSurfaceProps(occFace, uv[0], uv[1]);
          if (p) k = p.gaussian;
        } catch {
          // keep face-mean
        }
      }
      const rgb = vertexCurvatureColor(k, kMin, kMax);
      // Map the colour into one of BANDS by luminance along the ramp.
      const t = kMax > kMin ? (k - kMin) / (kMax - kMin) : 0.5;
      const band = Math.min(BANDS - 1, Math.max(0, Math.floor(t * BANDS)));
      buckets[band].push(triOf(face.vertices, i0, i1, i2));
      void rgb;
    }
  }
  const bands = buckets.map((tris, i) => {
    const t = BANDS <= 1 ? 0 : i / (BANDS - 1);
    return { name: `curv-${i}`, color: hex(vertexCurvatureColor(t, 0, 1)), tris };
  });
  const scriptPath = await writeOverlayScript(overlayDir, bands);
  return { ok: true, scriptPath };
}
