// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Andrii Shylenko and kernelCAD contributors
// tests/integration/export/attribution.test.ts
//
// Every exporter writes the kernelCAD generator string into the format's own
// metadata field (never into geometry), and the files stay valid. Reads each
// file back instead of trusting the writer.
import { describe, it, expect, beforeAll, beforeEach, afterEach } from 'vitest';
import { mkdtempSync, rmSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { NodeIO } from '@gltf-transform/core';
import { exportModelTool } from '../../../src/agent/mcp/tools/exportModel';
import { initOcct } from '../../../src/kernel/backends/occt/occtBackend';
import { inspectStepBuffer } from '../../../src/kernel/import/inspectStep';
import { readStepOriginatingSystem } from '../../../src/kernel/export/stepHeader';
import { urdfSerialize } from '../../../src/modeling/export/urdf/urdfSerializer';
import { srdfSerialize } from '../../../src/modeling/export/srdf/srdfSerializer';
import { sdfSerialize } from '../../../src/modeling/export/sdformat/sdfSerializer';
import { assemblyToMjcf } from '../../../src/modeling/runtime/mjcfExport';
import { CaptureSession } from '../../../src/modeling/capture/captureSession';
import { createModelingApi } from '../../../src/modeling/api';

const GENERATOR = /^kernelCAD \S+ \(https:\/\/kernelcad\.com\)$/;
/** Parse the JSON chunk of a GLB. glTF-Transform's reader drops asset.generator, so read it raw. */
function glbJson(bytes: Uint8Array): { asset: { generator?: string; extras?: Record<string, unknown> } } {
  const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);
  const len = view.getUint32(12, true);
  return JSON.parse(new TextDecoder().decode(bytes.subarray(20, 20 + len)));
}

const XML_COMMENT = /^<\?xml[^>]*\?>\n<!-- Generated by kernelCAD \S+ \(https:\/\/kernelcad\.com\) -->\n/;

beforeAll(async () => {
  await initOcct();
}, 60000);

let tmpDir: string;
beforeEach(() => {
  tmpDir = mkdtempSync(join(tmpdir(), 'kernelcad-attribution-'));
});
afterEach(() => {
  rmSync(tmpDir, { recursive: true, force: true });
});

async function exportTo(format: 'step' | 'stl' | 'glb' | 'dxf', code: string, name: string): Promise<Buffer> {
  const out = join(tmpDir, name);
  const r = await exportModelTool({ code, output_path: out, format });
  expect(r.ok).toBe(true);
  return readFileSync(out);
}

describe('export attribution', () => {
  it('STEP: FILE_NAME originating_system names kernelCAD; OCCT stays the preprocessor; file re-imports', async () => {
    const buf = await exportTo('step', 'return box(10, 10, 10);', 'box.step');
    expect(readStepOriginatingSystem(buf)).toMatch(GENERATOR);
    const header = buf.subarray(0, buf.indexOf('ENDSEC;')).toString('latin1');
    expect(header).toContain('Open CASCADE STEP processor');
    const report = await inspectStepBuffer(buf, 'box.step');
    expect(report.solidCount).toBe(1);
  }, 60000);

  it('STEP: a multi-part Scene export is stamped too', async () => {
    const buf = await exportTo('step', `
      const a = assembly('pair');
      a.part('a', box(10, 10, 10));
      a.part('b', box(10, 10, 10).translate(20, 0, 0));
      return a.model();
    `, 'pair.step');
    expect(readStepOriginatingSystem(buf)).toMatch(GENERATOR);
    const report = await inspectStepBuffer(buf, 'pair.step');
    expect(report.solidCount).toBe(2);
  }, 60000);

  it('STL: the 80-byte binary header names kernelCAD and the file is still binary STL', async () => {
    const buf = await exportTo('stl', 'return box(10, 10, 10);', 'box.stl');
    const header = buf.subarray(0, 80).toString('ascii').replace(/\0+$/, '');
    expect(header).toMatch(/^kernelCAD \S+ \(https:\/\/kernelcad\.com\) \d{4}-\d{2}-\d{2}$/);
    expect(buf.length).toBe(84 + buf.readUInt32LE(80) * 50);
  }, 60000);

  it('GLB: asset.generator names kernelCAD and the file parses', async () => {
    const buf = await exportTo('glb', 'return box(10, 10, 10);', 'box.glb');
    expect(glbJson(buf).asset.generator).toMatch(GENERATOR);
    const doc = await new NodeIO().readBinary(new Uint8Array(buf));
    expect(doc.getRoot().listMeshes().length).toBeGreaterThan(0);
  }, 60000);

  it('DXF: the first 999 comment names kernelCAD', async () => {
    const buf = await exportTo('dxf', `
      const s = path().moveTo(0, 0).lineTo(50, 0).lineTo(50, 25).lineTo(0, 25).close();
      return sheetMetal(s, { thickness: 1.0, kFactor: 0.4 });
    `, 'plate.dxf');
    const lines = buf.toString('utf8').split(/\r?\n/);
    expect(lines[0]).toBe('999');
    expect(lines[1]).toMatch(/^kernelCAD \S+ \(https:\/\/kernelcad\.com\) \d{4}-\d{2}-\d{2}$/);
    expect(lines).toContain('ENTITIES');
  }, 60000);

  describe('robot description XML', () => {
    function twoLink() {
      const kcad = createModelingApi({ session: new CaptureSession() });
      const arm = kcad.assembly('two-link');
      const base = arm.part('base', kcad.box(20, 20, 20), { density: 2700 });
      const link = arm.part('link', kcad.box(80, 10, 10), { density: 2700 });
      base.connector('shoulder', { type: 'axis', origin: { kind: 'vec3', value: [0, 0, 20] }, axis: [0, 0, 1] });
      link.connector('shoulder', { type: 'axis', origin: { kind: 'vec3', value: [0, 0, 0] }, axis: [0, 0, 1] });
      arm.mate('shoulder', 'base.shoulder', 'link.shoulder', 'revolute', { limitsDeg: [-90, 90] });
      arm.planningGroup('main', { chain: { baseLink: 'base', tipLink: 'link' } });
      return arm;
    }

    it('URDF, SRDF, SDF and MJCF carry a generator comment right after the XML declaration', async () => {
      const arm = twoLink();
      const urdf = (await urdfSerialize(arm, {})).urdf;
      const srdf = (await srdfSerialize(arm, {})).srdf;
      const sdf = (await sdfSerialize(arm, {})).sdf;
      const mjcf = (await assemblyToMjcf(arm)).mjcf;
      for (const xml of [urdf, srdf, sdf, mjcf]) {
        expect(xml).toMatch(XML_COMMENT);
      }
      expect(urdf).toMatch(/<robot name="two-link">/);
      expect(sdf).toMatch(/<sdf version=/);
      expect(mjcf).toMatch(/<mujoco model="two-link">/);
    }, 60000);
  });
});
