/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as MeRouteImport } from './routes/me'
import { Route as DemoPlayerRouteImport } from './routes/demo-player'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as GGenIdRouteImport } from './routes/g.$genId'

const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPlayerRoute = DemoPlayerRouteImport.update({
  id: '/demo-player',
  path: '/demo-player',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GGenIdRoute = GGenIdRouteImport.update({
  id: '/g/$genId',
  path: '/g/$genId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo-player': typeof DemoPlayerRoute
  '/me': typeof MeRoute
  '/signin': typeof SigninRoute
  '/studio': typeof StudioRoute
  '/g/$genId': typeof GGenIdRoute
  '/p/$slug': typeof PSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo-player': typeof DemoPlayerRoute
  '/me': typeof MeRoute
  '/signin': typeof SigninRoute
  '/studio': typeof StudioRoute
  '/g/$genId': typeof GGenIdRoute
  '/p/$slug': typeof PSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo-player': typeof DemoPlayerRoute
  '/me': typeof MeRoute
  '/signin': typeof SigninRoute
  '/studio': typeof StudioRoute
  '/g/$genId': typeof GGenIdRoute
  '/p/$slug': typeof PSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo-player'
    | '/me'
    | '/signin'
    | '/studio'
    | '/g/$genId'
    | '/p/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo-player'
    | '/me'
    | '/signin'
    | '/studio'
    | '/g/$genId'
    | '/p/$slug'
  id:
    | '__root__'
    | '/'
    | '/demo-player'
    | '/me'
    | '/signin'
    | '/studio'
    | '/g/$genId'
    | '/p/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoPlayerRoute: typeof DemoPlayerRoute
  MeRoute: typeof MeRoute
  SigninRoute: typeof SigninRoute
  StudioRoute: typeof StudioRoute
  GGenIdRoute: typeof GGenIdRoute
  PSlugRoute: typeof PSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo-player': {
      id: '/demo-player'
      path: '/demo-player'
      fullPath: '/demo-player'
      preLoaderRoute: typeof DemoPlayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/g/$genId': {
      id: '/g/$genId'
      path: '/g/$genId'
      fullPath: '/g/$genId'
      preLoaderRoute: typeof GGenIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoPlayerRoute: DemoPlayerRoute,
  MeRoute: MeRoute,
  SigninRoute: SigninRoute,
  StudioRoute: StudioRoute,
  GGenIdRoute: GGenIdRoute,
  PSlugRoute: PSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
